-- create new table for institution --

CREATE TABLE institution (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1000000000 INCREMENT BY 1) PRIMARY KEY,
  id_auth uuid NOT NULL ,
  name VARCHAR(25) NOT NULL DEFAULT 'Gesust',
  email VARCHAR(50) NOT NULL,
  description TEXT,
  dateEstablishment DATE DEFAULT CURRENT_DATE,
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(25) NOT NULL DEFAULT 'processing',
  FOREIGN KEY (id_auth) REFERENCES auth.users(id)
);

-- create new table for contact institution ----
CREATE TABLE contact (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  id_auth uuid NOT NULL ,
  id_institution bigint not null ,
  name_contact VARCHAR(25) NOT NULL ,
  value VARCHAR(50) NOT NULL,
  url TEXT,
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_auth) REFERENCES auth.users(id),
  FOREIGN KEY (id_institution) REFERENCES institution(id)
);