name: attendance_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  # security
  shelf_helmet: ^1.1.0
  shelf_rate_limiter: ^1.0.1
  content_length_validator: ^1.1.0
  sanitize_html: ^2.0.0

 # validator text
  string_validator: ^1.0.0
  regexed_validator: ^2.0.0+1



  # Database
  supabase: ^1.6.1
  shelf_enforces_ssl: ^1.1.0
  jwt_decoder: ^2.0.1
  supabase_extensions: ^0.5.1


dev_dependencies:
  http: ^0.13.5
  lints: ^2.0.1
  test: ^1.23.1
  shelf_hotreload: ^1.4.0




# Name
# AC57fba221e701ad1798ccc5db75c60144
# Database Password
# 370c03bcd657564504a1cb5094e2d5f2

# url 
# https://syfjvvgwactffitjmrqu.supabase.co
# anonpublic
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5Zmp2dmd3YWN0ZmZpdGptcnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzk3NzEwNTQsImV4cCI6MTk5NTM0NzA1NH0.B2LzNAeVVpQLpcx7LRhnN6_t2gDB0Pi3JuHR2Xb6LKk
# Host 
# db.syfjvvgwactffitjmrqu.supabase.co
# secret key
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5Zmp2dmd3YWN0ZmZpdGptcnF1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3OTc3MTA1NCwiZXhwIjoxOTk1MzQ3MDU0fQ.KZjKKzlg6Pvi1jn9WWCRaZt-7l0MjrCnv3VR7hH-0Uc
# JWT Secret
# RJiPI3GWrONHi35R56nzifYu235ApzlH6+mAF2B7//Zj78LDe2ul2lsHoec/Wv3vYycBQ4s6I1W1yIsqu4uHoA==