name: attendance_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  # security
  shelf_helmet: ^1.1.0
  shelf_rate_limiter: ^1.0.1
  content_length_validator: ^1.1.0
  sanitize_html: ^2.0.0

 # validator text
  string_validator: ^1.0.0
  regexed_validator: ^2.0.0+1



  # Database
  supabase: ^1.6.1
  shelf_enforces_ssl: ^1.1.0
  jwt_decoder: ^2.0.1
  supabase_extensions: ^0.5.1


dev_dependencies:
  http: ^0.13.5
  lints: ^2.0.1
  test: ^1.23.1
  shelf_hotreload: ^1.4.0




